spring.application.name=GestorElectivosJava

# Se debe configurar la conexion a la base de datos Postgres SQL


# Configuración de la base de datos PostgreSQ
spring.datasource.url=jdbc:postgresql://localhost:5432/gestorElectivosJava
spring.datasource.username=postgres
spring.datasource.password=123

spring.security.user.name=user1
spring.security.user.password=12345

# spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA (Hibernate)

spring.jpa.hibernate.ddl-auto=update

# Se especifica el dialecto, garantizando la compatibilidad y el rendimiento óptimo
# de tu API de Spring Boot al interactuar con la base de datos.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Usa 'none' en producción.

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.


#Opcional: Configuración del servidor para que sea más claro

#server.port=8080
#server.servlet.context-path=/gestor-electivos
